import './globals.css'


export const metadata: Metadata = {
  title: 'Kanba Bord',
  description: 'Generated by Atharva Naik',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className='bg-[#f5f6f8]'>{children}</body>
    </html>
  )
}
